FlutterFlowDropDown<String>(
  controller: _model.districtDropDownValueController ??=
      FormFieldController<String>(null),
  options: [
    '中西區',
    '灣仔區',
    '東區',
    '南區',
    '油尖旺區',
    '深水埗區',
    '九龍城區',
    '黃大仙區',
    '觀塘區',
    '葵青區',
    '荃灣區',
    '屯門區',
    '元朗區',
    '北區',
    '大埔區',
    '沙田區',
    '西貢區',
    '離島區'
  ],
  onChanged: (val) => setState(() => _model.districtDropDownValue = val),
  width: double.infinity,
  height: 50.0,
  textStyle: FlutterFlowTheme.of(context).bodyMedium.override(
        fontFamily: 'Montserrat',
        letterSpacing: 0.0,
      ),
  hintText: '請選擇地區',
  icon: Icon(
    Icons.keyboard_arrow_down_rounded,
    color: FlutterFlowTheme.of(context).secondaryText,
    size: 24.0,
  ),
  fillColor: FlutterFlowTheme.of(context).secondaryBackground,
  elevation: 2.0,
  borderColor: FlutterFlowTheme.of(context).alternate,
  borderWidth: 2.0,
  borderRadius: 8.0,
  margin: EdgeInsetsDirectional.fromSTEB(16.0, 4.0, 16.0, 4.0),
  hidesUnderline: true,
  isSearchable: false,
  isMultiSelect: false,
),
FlutterFlowDropDown<String>(
  controller: _model.expertiseDropDownValueController ??=
      FormFieldController<String>(null),
  options: [
    '註冊護士（普通科）',
    '註冊護士（精神科）',
    '登記護士（普通科）',
    '登記護士（精神科）',
    '保健員',
    '醫護支援人員',
    '起居照顧員',
    '護士學生',
    '陪月',
    '保健員',
    '陪診員',
    '病人服務助理',
  ],
  onChanged: (val) => setState(() => _model.expertiseDropDownValue = val),
  width: double.infinity,
  height: 56,
  textStyle: FlutterFlowTheme.of(context).bodyMedium,
  hintText: '請選擇專業',
  icon: Icon(
    Icons.keyboard_arrow_down_rounded,
    color: FlutterFlowTheme.of(context).secondaryText,
    size: 24,
  ),
  fillColor: FlutterFlowTheme.of(context).secondaryBackground,
  elevation: 2,
  borderColor: FlutterFlowTheme.of(context).alternate,
  borderWidth: 2,
  borderRadius: 12,
  margin: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
  hidesUnderline: true,
  isSearchable: false,
),
FlutterFlowDropDown<String>(
  controller: _model.howKnowDropDownValueController ??= FormFieldController<String>(null),
  options: [
    '社交媒體',
    '朋友或家人',
    '網上搜尋',
    '廣告',
    '活動或工作坊',
    '其他',
  ],
  onChanged: (val) => setState(() => _model.howKnowDropDownValue = val),
  height: 56,
  textStyle: FlutterFlowTheme.of(context).bodyMedium,
  hintText: '請選擇',
  icon: Icon(
    Icons.keyboard_arrow_down_rounded,
    color: FlutterFlowTheme.of(context).secondaryText,
    size: 24,
  ),
  fillColor: FlutterFlowTheme.of(context).secondaryBackground,
  elevation: 2,
  borderColor: FlutterFlowTheme.of(context).alternate,
  borderWidth: 2,
  borderRadius: 12,
  margin: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
  hidesUnderline: true,
  isSearchable: false,
), 
 